/**
 * Curated system-design practice questions, grouped by track.
 *
 * Keep prompts short and self-contained. The user can still elaborate before
 * starting a session. Requirements are generated by the LLM (same flow as
 * custom prompts), so we don't pre-bake them here.
 */

export type QuestionCategory = "backend" | "android" | "ios";

export type BankQuestion = {
  id: string;
  category: QuestionCategory;
  title: string;
  prompt: string;
  difficulty: "easy" | "medium" | "hard";
  tags?: string[];
};

export const CATEGORY_LABEL: Record<QuestionCategory, string> = {
  backend: "Backend",
  android: "Mobile · Android",
  ios: "Mobile · iOS",
};

const BACKEND: BankQuestion[] = [
  {
    id: "be-url-shortener",
    category: "backend",
    title: "URL Shortener (bit.ly)",
    prompt:
      "Design a URL shortening service like bit.ly that maps long URLs to short aliases, supports redirection, custom aliases, expiration, and basic analytics (click counts).",
    difficulty: "easy",
    tags: ["hashing", "kv-store", "cache"],
  },
  {
    id: "be-pastebin",
    category: "backend",
    title: "Pastebin",
    prompt:
      "Design a Pastebin-like service where users can paste text snippets and share them via a unique URL. Support expiration, syntax highlighting, and view counts.",
    difficulty: "easy",
    tags: ["object-storage", "cache"],
  },
  {
    id: "be-rate-limiter",
    category: "backend",
    title: "Distributed Rate Limiter",
    prompt:
      "Design a distributed rate limiter that supports per-user and per-IP limits across many API gateway nodes. Discuss algorithms (token bucket, sliding window) and consistency trade-offs.",
    difficulty: "medium",
    tags: ["redis", "algorithms"],
  },
  {
    id: "be-twitter",
    category: "backend",
    title: "Twitter / X Timeline",
    prompt:
      "Design Twitter: posting tweets, following users, and a home timeline that scales to hundreds of millions of users. Discuss fan-out on write vs read and timeline storage.",
    difficulty: "hard",
    tags: ["timeline", "fan-out", "cache"],
  },
  {
    id: "be-instagram",
    category: "backend",
    title: "Instagram Feed",
    prompt:
      "Design Instagram: photo upload, profile pages, follow graph, and a personalized photo/video feed. Cover image storage, CDN delivery, and feed ranking.",
    difficulty: "hard",
    tags: ["media", "cdn", "feed"],
  },
  {
    id: "be-youtube",
    category: "backend",
    title: "YouTube / Video Streaming",
    prompt:
      "Design a video streaming platform like YouTube. Cover upload pipeline, transcoding, adaptive bitrate streaming, CDN distribution, search, and view analytics.",
    difficulty: "hard",
    tags: ["video", "transcoding", "cdn"],
  },
  {
    id: "be-whatsapp",
    category: "backend",
    title: "WhatsApp / Chat Service",
    prompt:
      "Design a real-time chat service supporting 1:1 and group chats, message ordering, delivery + read receipts, presence, and offline message delivery for ~1B users.",
    difficulty: "hard",
    tags: ["websocket", "queue", "sharding"],
  },
  {
    id: "be-uber",
    category: "backend",
    title: "Uber / Ride Matching",
    prompt:
      "Design the backend that matches riders with nearby drivers in real time, tracks driver locations, computes ETAs and fares, and handles trip lifecycle.",
    difficulty: "hard",
    tags: ["geospatial", "real-time", "matching"],
  },
  {
    id: "be-dropbox",
    category: "backend",
    title: "Dropbox / File Sync",
    prompt:
      "Design a cloud file storage service with multi-device sync, file versioning, sharing, and conflict resolution. Discuss chunking, deduplication, and delta sync.",
    difficulty: "hard",
    tags: ["sync", "chunking", "blob-store"],
  },
  {
    id: "be-newsfeed",
    category: "backend",
    title: "Facebook News Feed",
    prompt:
      "Design the news feed for a social network: ranking, generation, caching, and serving feeds with low latency under heavy fan-out.",
    difficulty: "hard",
    tags: ["feed", "ranking", "cache"],
  },
  {
    id: "be-search-autocomplete",
    category: "backend",
    title: "Search Autocomplete",
    prompt:
      "Design a typeahead/autocomplete service that returns top suggestions in <100ms based on real-time popularity and personalization.",
    difficulty: "medium",
    tags: ["trie", "ranking", "cache"],
  },
  {
    id: "be-notification",
    category: "backend",
    title: "Notification System",
    prompt:
      "Design a system that sends notifications across email, SMS, and push at high throughput with retries, deduplication, user preferences, and rate limits.",
    difficulty: "medium",
    tags: ["queue", "fanout", "providers"],
  },
  {
    id: "be-message-queue",
    category: "backend",
    title: "Distributed Message Queue (Kafka)",
    prompt:
      "Design a distributed pub/sub message queue with partitioning, replication, durable storage, consumer groups, and exactly-once-ish semantics.",
    difficulty: "hard",
    tags: ["streaming", "replication", "partitioning"],
  },
  {
    id: "be-web-crawler",
    category: "backend",
    title: "Web Crawler",
    prompt:
      "Design a polite, distributed web crawler that fetches billions of pages, respects robots.txt, deduplicates URLs, and feeds a search index.",
    difficulty: "hard",
    tags: ["crawler", "queue", "deduplication"],
  },
  {
    id: "be-payment",
    category: "backend",
    title: "Payment Processing",
    prompt:
      "Design a payment system that processes card and wallet transactions with idempotency, retries, fraud checks, and double-entry ledgering.",
    difficulty: "hard",
    tags: ["transactions", "ledger", "idempotency"],
  },
  {
    id: "be-yelp",
    category: "backend",
    title: "Yelp / Nearby Places",
    prompt:
      "Design a geo-search service that returns nearby businesses with reviews, photos, and filters at low latency.",
    difficulty: "medium",
    tags: ["geospatial", "search", "ranking"],
  },
  {
    id: "be-ticketmaster",
    category: "backend",
    title: "Ticketmaster / Seat Booking",
    prompt:
      "Design a ticket booking system that prevents double-booking under spike traffic with seat reservations, payments, and waitlists.",
    difficulty: "medium",
    tags: ["locking", "transactions", "queue"],
  },
  {
    id: "be-google-docs",
    category: "backend",
    title: "Google Docs / Collaborative Editor",
    prompt:
      "Design a real-time collaborative document editor with concurrent edits, cursors, comments, and version history. Discuss CRDTs vs OT.",
    difficulty: "hard",
    tags: ["crdt", "websocket", "versioning"],
  },
  {
    id: "be-distributed-cache",
    category: "backend",
    title: "Distributed Cache",
    prompt:
      "Design a distributed in-memory cache like Memcached / Redis Cluster: sharding, replication, eviction, and client routing.",
    difficulty: "medium",
    tags: ["sharding", "replication", "consistent-hashing"],
  },
  {
    id: "be-api-gateway",
    category: "backend",
    title: "API Gateway",
    prompt:
      "Design an API gateway that handles routing, auth, rate limiting, request/response transformation, and observability for hundreds of microservices.",
    difficulty: "medium",
    tags: ["proxy", "auth", "observability"],
  },
];

const ANDROID: BankQuestion[] = [
  {
    id: "and-instagram-feed",
    category: "android",
    title: "Instagram Feed (Android)",
    prompt:
      "Design the Android client for Instagram: paginated photo/video feed, image caching, prefetching, offline viewing of recently seen posts, smooth scroll on low-end devices.",
    difficulty: "medium",
    tags: ["recyclerview", "image-cache", "paging"],
  },
  {
    id: "and-whatsapp-client",
    category: "android",
    title: "WhatsApp Mobile Client (Android)",
    prompt:
      "Design the Android WhatsApp app: local chat database (Room/SQLite), background sync, push notifications, end-to-end encryption keys, attachments, and offline-first messaging.",
    difficulty: "hard",
    tags: ["room", "workmanager", "fcm", "e2ee"],
  },
  {
    id: "and-uber-rider",
    category: "android",
    title: "Uber Rider (Android)",
    prompt:
      "Design the Android Uber rider app: live driver tracking on a map, ETA updates, foreground location, payments, and graceful degradation on poor networks.",
    difficulty: "hard",
    tags: ["maps", "location", "websocket"],
  },
  {
    id: "and-spotify-offline",
    category: "android",
    title: "Spotify Offline Playback (Android)",
    prompt:
      "Design Spotify on Android: streaming + offline downloads, encrypted local cache, background audio playback, MediaSession integration, and bandwidth-aware adaptive streaming.",
    difficulty: "hard",
    tags: ["mediasession", "exoplayer", "drm", "storage"],
  },
  {
    id: "and-news-reader",
    category: "android",
    title: "News Reader (Android)",
    prompt:
      "Design an Android news reader with offline articles, image caching, push for breaking news, and read-later sync across devices.",
    difficulty: "medium",
    tags: ["paging", "workmanager", "cache"],
  },
  {
    id: "and-photo-backup",
    category: "android",
    title: "Photo Backup / Google Photos (Android)",
    prompt:
      "Design the Android photo backup client: scan local gallery, upload deltas in background, dedup, handle metered networks, low battery, and resume after reboot.",
    difficulty: "hard",
    tags: ["mediastore", "workmanager", "battery"],
  },
  {
    id: "and-ride-share-driver",
    category: "android",
    title: "Ride-Share Driver App (Android)",
    prompt:
      "Design the Android driver app: continuous foreground location, trip lifecycle, voice navigation, offline trip queueing, and driver heat-map.",
    difficulty: "hard",
    tags: ["foreground-service", "location", "battery"],
  },
  {
    id: "and-food-delivery",
    category: "android",
    title: "Food Delivery App (Android)",
    prompt:
      "Design the Android food delivery app: restaurant browsing, cart, payments, real-time order tracking via map + push updates, and rating flow.",
    difficulty: "medium",
    tags: ["maps", "push", "payments"],
  },
  {
    id: "and-video-conferencing",
    category: "android",
    title: "Video Conferencing (Android)",
    prompt:
      "Design an Android Zoom-like client: camera + mic capture, WebRTC signaling, adaptive bitrate, background blur, picture-in-picture.",
    difficulty: "hard",
    tags: ["webrtc", "camerax", "pip"],
  },
  {
    id: "and-banking",
    category: "android",
    title: "Mobile Banking (Android)",
    prompt:
      "Design a secure Android banking app: biometric auth, encrypted local storage, jailbreak/root detection, transaction list pagination, and offline view of recent statements.",
    difficulty: "hard",
    tags: ["biometric", "keystore", "security"],
  },
  {
    id: "and-notes",
    category: "android",
    title: "Offline-First Notes (Android)",
    prompt:
      "Design an Android notes app with offline editing, conflict-free sync across devices, search, attachments, and end-to-end encryption.",
    difficulty: "medium",
    tags: ["sync", "crdt", "room"],
  },
  {
    id: "and-fitness-tracker",
    category: "android",
    title: "Fitness Tracker (Android)",
    prompt:
      "Design an Android fitness tracker that runs continuously in background, samples sensors (GPS, accelerometer, heart rate), conserves battery, and syncs workouts to a backend.",
    difficulty: "hard",
    tags: ["sensors", "foreground-service", "battery"],
  },
  {
    id: "and-stories",
    category: "android",
    title: "Stories / Reels Capture (Android)",
    prompt:
      "Design the Android capture-and-share story flow: camera preview, filters, video trim, upload with retry, pre-cache for next viewer.",
    difficulty: "medium",
    tags: ["camerax", "media-codec", "upload"],
  },
];

const IOS: BankQuestion[] = [
  {
    id: "ios-instagram-feed",
    category: "ios",
    title: "Instagram Feed (iOS)",
    prompt:
      "Design the iOS Instagram client: smooth UICollectionView feed, image prefetch, disk + memory cache, low-data mode handling, and accessibility.",
    difficulty: "medium",
    tags: ["uicollectionview", "nscache", "prefetch"],
  },
  {
    id: "ios-whatsapp-client",
    category: "ios",
    title: "WhatsApp Mobile Client (iOS)",
    prompt:
      "Design the iOS WhatsApp app: Core Data / SQLite chat store, background fetch, VoIP push, end-to-end encryption, attachments via NSURLSession background config.",
    difficulty: "hard",
    tags: ["coredata", "background-modes", "voip-push", "e2ee"],
  },
  {
    id: "ios-apple-maps",
    category: "ios",
    title: "Apple Maps / Navigation (iOS)",
    prompt:
      "Design the iOS turn-by-turn navigation app: offline map tiles, route calculation, location updates, CarPlay integration, and battery-aware GPS sampling.",
    difficulty: "hard",
    tags: ["mapkit", "corelocation", "carplay", "battery"],
  },
  {
    id: "ios-spotify-offline",
    category: "ios",
    title: "Spotify Offline Playback (iOS)",
    prompt:
      "Design Spotify on iOS: AVAudioSession-based background playback, offline downloads via NSURLSession, MPRemoteCommandCenter, lock-screen art, and adaptive streaming.",
    difficulty: "hard",
    tags: ["avaudiosession", "background-audio", "remote-command"],
  },
  {
    id: "ios-photos-app",
    category: "ios",
    title: "Photo Library / iCloud Photos (iOS)",
    prompt:
      "Design an iOS photos app: scan PHAsset library, dedupe, lazy-load thumbnails, sync deltas to backend on Wi-Fi only, handle low storage and HEIC.",
    difficulty: "hard",
    tags: ["photokit", "background-task", "heic"],
  },
  {
    id: "ios-news-reader",
    category: "ios",
    title: "News Reader (iOS)",
    prompt:
      "Design an iOS news reader with offline articles, dynamic type support, push for breaking news, and read-later sync via CloudKit.",
    difficulty: "medium",
    tags: ["uikit", "cloudkit", "background-fetch"],
  },
  {
    id: "ios-uber-rider",
    category: "ios",
    title: "Uber Rider (iOS)",
    prompt:
      "Design the iOS Uber rider app: live map, ETA, payments via Apple Pay, real-time updates over WebSocket, and graceful handling of permission denials.",
    difficulty: "hard",
    tags: ["mapkit", "websocket", "applepay"],
  },
  {
    id: "ios-ride-share-driver",
    category: "ios",
    title: "Ride-Share Driver App (iOS)",
    prompt:
      "Design the iOS driver app: continuous background location with battery efficiency, region monitoring for hotspots, trip lifecycle, and CarPlay support.",
    difficulty: "hard",
    tags: ["corelocation", "background-modes", "carplay"],
  },
  {
    id: "ios-food-delivery",
    category: "ios",
    title: "Food Delivery App (iOS)",
    prompt:
      "Design the iOS food delivery app: restaurant browsing, cart with state restoration, Apple Pay checkout, real-time tracking, and live activities on the lock screen.",
    difficulty: "medium",
    tags: ["live-activities", "applepay", "push"],
  },
  {
    id: "ios-video-conferencing",
    category: "ios",
    title: "Video Conferencing (iOS)",
    prompt:
      "Design an iOS Zoom-like client: AVCaptureSession for camera/mic, WebRTC, picture-in-picture, CallKit for incoming calls, and bandwidth adaptation.",
    difficulty: "hard",
    tags: ["webrtc", "callkit", "pip"],
  },
  {
    id: "ios-banking",
    category: "ios",
    title: "Mobile Banking (iOS)",
    prompt:
      "Design a secure iOS banking app: Face ID / Touch ID, Keychain-stored credentials, jailbreak detection, and offline view of recent transactions.",
    difficulty: "hard",
    tags: ["localauth", "keychain", "security"],
  },
  {
    id: "ios-notes",
    category: "ios",
    title: "Offline-First Notes (iOS)",
    prompt:
      "Design an iOS notes app with offline editing, sync via CloudKit, full-text search, attachments, and end-to-end encryption.",
    difficulty: "medium",
    tags: ["cloudkit", "coredata", "sync"],
  },
  {
    id: "ios-fitness",
    category: "ios",
    title: "Fitness / Health Tracker (iOS)",
    prompt:
      "Design an iOS fitness tracker integrated with HealthKit: workout sessions, GPS + heart rate sampling, Apple Watch companion, and battery-aware background updates.",
    difficulty: "hard",
    tags: ["healthkit", "watch", "background-modes"],
  },
];

export const QUESTION_BANK: BankQuestion[] = [...BACKEND, ...ANDROID, ...IOS];

export function getQuestionsByCategory(category: QuestionCategory): BankQuestion[] {
  return QUESTION_BANK.filter((q) => q.category === category);
}

export function getQuestionById(id: string): BankQuestion | undefined {
  return QUESTION_BANK.find((q) => q.id === id);
}
